/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SponsorRouteImport } from './routes/sponsor'
import { Route as ServiceProviderRouteImport } from './routes/service-provider'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NegotiatorRouteImport } from './routes/negotiator'
import { Route as MarketingRouteImport } from './routes/marketing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DistributorRouteImport } from './routes/distributor'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as OrganizerRouteRouteImport } from './routes/organizer/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrganizerIndexRouteImport } from './routes/organizer/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as EventsEventIdRouteImport } from './routes/events/$eventId'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminPermissionsRouteImport } from './routes/admin/permissions'
import { Route as AdminNavigationRouteImport } from './routes/admin/navigation'
import { Route as AdminLogsRouteImport } from './routes/admin/logs'
import { Route as AdminEventsRouteImport } from './routes/admin/events'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminCapabilitiesRouteImport } from './routes/admin/capabilities'
import { Route as OrganizerEventsNewRouteImport } from './routes/organizer/events/new'
import { Route as OrganizerEventsEventIdEditRouteImport } from './routes/organizer/events/$eventId.edit'
import { Route as AdminUsersUserIdCapsRouteImport } from './routes/admin/users.$userId.caps'
import { ServerRoute as ApiAuthSplatServerRouteImport } from './routes/api/auth.$'

const rootServerRouteImport = createServerRootRoute()

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorRoute = SponsorRouteImport.update({
  id: '/sponsor',
  path: '/sponsor',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceProviderRoute = ServiceProviderRouteImport.update({
  id: '/service-provider',
  path: '/service-provider',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NegotiatorRoute = NegotiatorRouteImport.update({
  id: '/negotiator',
  path: '/negotiator',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DistributorRoute = DistributorRouteImport.update({
  id: '/distributor',
  path: '/distributor',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerRouteRoute = OrganizerRouteRouteImport.update({
  id: '/organizer',
  path: '/organizer',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerIndexRoute = OrganizerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrganizerRouteRoute,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPermissionsRoute = AdminPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNavigationRoute = AdminNavigationRouteImport.update({
  id: '/navigation',
  path: '/navigation',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCapabilitiesRoute = AdminCapabilitiesRouteImport.update({
  id: '/capabilities',
  path: '/capabilities',
  getParentRoute: () => AdminRouteRoute,
} as any)
const OrganizerEventsNewRoute = OrganizerEventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => OrganizerRouteRoute,
} as any)
const OrganizerEventsEventIdEditRoute =
  OrganizerEventsEventIdEditRouteImport.update({
    id: '/events/$eventId/edit',
    path: '/events/$eventId/edit',
    getParentRoute: () => OrganizerRouteRoute,
  } as any)
const AdminUsersUserIdCapsRoute = AdminUsersUserIdCapsRouteImport.update({
  id: '/$userId/caps',
  path: '/$userId/caps',
  getParentRoute: () => AdminUsersRoute,
} as any)
const ApiAuthSplatServerRoute = ApiAuthSplatServerRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/organizer': typeof OrganizerRouteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/distributor': typeof DistributorRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/marketing': typeof MarketingRoute
  '/negotiator': typeof NegotiatorRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/service-provider': typeof ServiceProviderRoute
  '/sponsor': typeof SponsorRoute
  '/staff': typeof StaffRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/capabilities': typeof AdminCapabilitiesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/events/$eventId': typeof EventsEventIdRoute
  '/admin/': typeof AdminIndexRoute
  '/events': typeof EventsIndexRoute
  '/organizer/': typeof OrganizerIndexRoute
  '/organizer/events/new': typeof OrganizerEventsNewRoute
  '/admin/users/$userId/caps': typeof AdminUsersUserIdCapsRoute
  '/organizer/events/$eventId/edit': typeof OrganizerEventsEventIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/distributor': typeof DistributorRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/marketing': typeof MarketingRoute
  '/negotiator': typeof NegotiatorRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/service-provider': typeof ServiceProviderRoute
  '/sponsor': typeof SponsorRoute
  '/staff': typeof StaffRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/capabilities': typeof AdminCapabilitiesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/events/$eventId': typeof EventsEventIdRoute
  '/admin': typeof AdminIndexRoute
  '/events': typeof EventsIndexRoute
  '/organizer': typeof OrganizerIndexRoute
  '/organizer/events/new': typeof OrganizerEventsNewRoute
  '/admin/users/$userId/caps': typeof AdminUsersUserIdCapsRoute
  '/organizer/events/$eventId/edit': typeof OrganizerEventsEventIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/organizer': typeof OrganizerRouteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/distributor': typeof DistributorRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/marketing': typeof MarketingRoute
  '/negotiator': typeof NegotiatorRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/service-provider': typeof ServiceProviderRoute
  '/sponsor': typeof SponsorRoute
  '/staff': typeof StaffRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/capabilities': typeof AdminCapabilitiesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/events/$eventId': typeof EventsEventIdRoute
  '/admin/': typeof AdminIndexRoute
  '/events/': typeof EventsIndexRoute
  '/organizer/': typeof OrganizerIndexRoute
  '/organizer/events/new': typeof OrganizerEventsNewRoute
  '/admin/users/$userId/caps': typeof AdminUsersUserIdCapsRoute
  '/organizer/events/$eventId/edit': typeof OrganizerEventsEventIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/organizer'
    | '/dashboard'
    | '/distributor'
    | '/forgot-password'
    | '/login'
    | '/marketing'
    | '/negotiator'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/service-provider'
    | '/sponsor'
    | '/staff'
    | '/verify-email'
    | '/admin/capabilities'
    | '/admin/categories'
    | '/admin/events'
    | '/admin/logs'
    | '/admin/navigation'
    | '/admin/permissions'
    | '/admin/users'
    | '/events/$eventId'
    | '/admin/'
    | '/events'
    | '/organizer/'
    | '/organizer/events/new'
    | '/admin/users/$userId/caps'
    | '/organizer/events/$eventId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/distributor'
    | '/forgot-password'
    | '/login'
    | '/marketing'
    | '/negotiator'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/service-provider'
    | '/sponsor'
    | '/staff'
    | '/verify-email'
    | '/admin/capabilities'
    | '/admin/categories'
    | '/admin/events'
    | '/admin/logs'
    | '/admin/navigation'
    | '/admin/permissions'
    | '/admin/users'
    | '/events/$eventId'
    | '/admin'
    | '/events'
    | '/organizer'
    | '/organizer/events/new'
    | '/admin/users/$userId/caps'
    | '/organizer/events/$eventId/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/organizer'
    | '/dashboard'
    | '/distributor'
    | '/forgot-password'
    | '/login'
    | '/marketing'
    | '/negotiator'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/service-provider'
    | '/sponsor'
    | '/staff'
    | '/verify-email'
    | '/admin/capabilities'
    | '/admin/categories'
    | '/admin/events'
    | '/admin/logs'
    | '/admin/navigation'
    | '/admin/permissions'
    | '/admin/users'
    | '/events/$eventId'
    | '/admin/'
    | '/events/'
    | '/organizer/'
    | '/organizer/events/new'
    | '/admin/users/$userId/caps'
    | '/organizer/events/$eventId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  OrganizerRouteRoute: typeof OrganizerRouteRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DistributorRoute: typeof DistributorRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MarketingRoute: typeof MarketingRoute
  NegotiatorRoute: typeof NegotiatorRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServiceProviderRoute: typeof ServiceProviderRoute
  SponsorRoute: typeof SponsorRoute
  StaffRoute: typeof StaffRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  EventsIndexRoute: typeof EventsIndexRoute
}
export interface FileServerRoutesByFullPath {
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRoutesByTo {
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/auth/$'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/auth/$'
  id: '__root__' | '/api/auth/$'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiAuthSplatServerRoute: typeof ApiAuthSplatServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsor': {
      id: '/sponsor'
      path: '/sponsor'
      fullPath: '/sponsor'
      preLoaderRoute: typeof SponsorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-provider': {
      id: '/service-provider'
      path: '/service-provider'
      fullPath: '/service-provider'
      preLoaderRoute: typeof ServiceProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/negotiator': {
      id: '/negotiator'
      path: '/negotiator'
      fullPath: '/negotiator'
      preLoaderRoute: typeof NegotiatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distributor': {
      id: '/distributor'
      path: '/distributor'
      fullPath: '/distributor'
      preLoaderRoute: typeof DistributorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer': {
      id: '/organizer'
      path: '/organizer'
      fullPath: '/organizer'
      preLoaderRoute: typeof OrganizerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/': {
      id: '/organizer/'
      path: '/'
      fullPath: '/organizer/'
      preLoaderRoute: typeof OrganizerIndexRouteImport
      parentRoute: typeof OrganizerRouteRoute
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/permissions': {
      id: '/admin/permissions'
      path: '/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AdminPermissionsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/navigation': {
      id: '/admin/navigation'
      path: '/navigation'
      fullPath: '/admin/navigation'
      preLoaderRoute: typeof AdminNavigationRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/capabilities': {
      id: '/admin/capabilities'
      path: '/capabilities'
      fullPath: '/admin/capabilities'
      preLoaderRoute: typeof AdminCapabilitiesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/organizer/events/new': {
      id: '/organizer/events/new'
      path: '/events/new'
      fullPath: '/organizer/events/new'
      preLoaderRoute: typeof OrganizerEventsNewRouteImport
      parentRoute: typeof OrganizerRouteRoute
    }
    '/organizer/events/$eventId/edit': {
      id: '/organizer/events/$eventId/edit'
      path: '/events/$eventId/edit'
      fullPath: '/organizer/events/$eventId/edit'
      preLoaderRoute: typeof OrganizerEventsEventIdEditRouteImport
      parentRoute: typeof OrganizerRouteRoute
    }
    '/admin/users/$userId/caps': {
      id: '/admin/users/$userId/caps'
      path: '/$userId/caps'
      fullPath: '/admin/users/$userId/caps'
      preLoaderRoute: typeof AdminUsersUserIdCapsRouteImport
      parentRoute: typeof AdminUsersRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface AdminUsersRouteChildren {
  AdminUsersUserIdCapsRoute: typeof AdminUsersUserIdCapsRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersUserIdCapsRoute: AdminUsersUserIdCapsRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminCapabilitiesRoute: typeof AdminCapabilitiesRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminNavigationRoute: typeof AdminNavigationRoute
  AdminPermissionsRoute: typeof AdminPermissionsRoute
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminCapabilitiesRoute: AdminCapabilitiesRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminNavigationRoute: AdminNavigationRoute,
  AdminPermissionsRoute: AdminPermissionsRoute,
  AdminUsersRoute: AdminUsersRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface OrganizerRouteRouteChildren {
  OrganizerIndexRoute: typeof OrganizerIndexRoute
  OrganizerEventsNewRoute: typeof OrganizerEventsNewRoute
  OrganizerEventsEventIdEditRoute: typeof OrganizerEventsEventIdEditRoute
}

const OrganizerRouteRouteChildren: OrganizerRouteRouteChildren = {
  OrganizerIndexRoute: OrganizerIndexRoute,
  OrganizerEventsNewRoute: OrganizerEventsNewRoute,
  OrganizerEventsEventIdEditRoute: OrganizerEventsEventIdEditRoute,
}

const OrganizerRouteRouteWithChildren = OrganizerRouteRoute._addFileChildren(
  OrganizerRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  OrganizerRouteRoute: OrganizerRouteRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DistributorRoute: DistributorRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MarketingRoute: MarketingRoute,
  NegotiatorRoute: NegotiatorRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServiceProviderRoute: ServiceProviderRoute,
  SponsorRoute: SponsorRoute,
  StaffRoute: StaffRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  EventsIndexRoute: EventsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiAuthSplatServerRoute: ApiAuthSplatServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
